[package]
name = "sui-transaction-builder"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.64"
async-trait = "0.1.57"
jsonrpsee = { version = "0.15.1", features = ["full"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.83"
futures-core = "0.3.21"
futures = "0.3.23"
signature = "1.6.0"
tokio = "1.20.1"
rand = "0.8.5"
bcs = "0.1.3"
tiny-bip39 = "1.0.0"
bip32 = "0.4.0"

sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-adapter =  { path = "../sui-adapter" }

move-core-types.workspace = true
move-bytecode-utils.workspace = true
move-binary-format.workspace = true

workspace-hack.workspace = true