#                                                             
#             +----------+      2                               
#    +------->|    B     |-------------+                        
#    |        +----------+             |                        
#    |                                 |                        
#    |                                 v                        
#  +----+     +----------+   3   +----------+                   
#  |Root|---->| A-rename | ----->| C-rename |                   
#  +----+     +----------+       +----------+                   
#    |                                 ^                        
#    |                                 |                        
#    +---------------------------------+    
#                  ov(1)
#

[package]
name = "Root"

[dependencies]
A-rename = { local = "./deps_only/A-rename" }
B = { local = "./deps_only/B" }
C-rename = { local = "./deps_only/C-rename-v1", override = true }
