{{- if .Values.frontendConfig }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.frontendConfig.name }}
spec:
  sslPolicy: {{ .Values.frontendConfig.spec.sslPolicy }}
  redirectToHttps:
    enabled: {{ .Values.frontendConfig.spec.redirectToHttps }}
{{- end }}
