{{- if .Values.multiclusterIngress.enabled }}
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: {{ .Values.multiclusterIngress.name }}
  annotations:
    networking.gke.io/static-ip: {{ .Values.multiclusterIngress.annotations.staticIp }}
    networking.gke.io/frontend-config: {{ .Values.multiclusterIngress.annotations.frontendConfig }}
spec:
  template:
    spec:
      backend:
        serviceName: {{ .Values.multiclusterIngress.spec.backend.serviceName }}
        servicePort: {{ .Values.multiclusterIngress.spec.backend.servicePort }}
      rules:
      {{- range .Values.multiclusterIngress.spec.rules }}
      - host: {{ .host }}
        http:
          paths:
          {{- range .http.paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .backend.serviceName }}
              servicePort: {{ .backend.servicePort }}
          {{- end }}
      {{- end }}
      tls:
      {{- range .Values.multiclusterIngress.spec.tls }}
      - secretName: {{ .secretName }}
      {{- end }}
{{- end }}
