[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
rand.workspace = true
prometheus.workspace = true

move-bytecode-utils.workspace = true
shared-crypto.workspace = true
sui-config.workspace = true
sui-protocol-config.workspace = true
sui-types.workspace = true
sui-execution.workspace = true
sui-swarm-config.workspace = true
sui-transaction-checks.workspace = true
workspace-hack.workspace = true
