[workspace]
members = [
        "fastpay_core",
        "fastpay",
        "fastx_programmability/adapter",
        "fastx_programmability/framework",
	"fastx_types",
]

[profile.release]
debug = true

[profile.bench]
debug = true

# Stopgap, remove when https://github.com/rust-rocksdb/rust-rocksdb/issues/602 is fixed
[patch.crates-io]
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb/", rev="626ff7e79dca107f76e347c3e1ea9cdabbd9d679" }
librocksdb-sys = { git = "https://github.com/rust-rocksdb/rust-rocksdb/", rev="626ff7e79dca107f76e347c3e1ea9cdabbd9d679" }
