[workspace]
members = [
    "crates/sui-adapter",
    "crates/sui-adapter-transactional-tests",
    "crates/sui-config",
    "crates/sui-faucet",
    "crates/sui-network",
    "crates/sui-transactional-test-runner",
    "crates/sui-types",
    "crates/sui-verifier",
    "crates/x",
    "sui",
    "sui/open_rpc",
    "sui/open_rpc/macros",
    "sui_core",
    "sui_programmability/framework",
    "sui_storage",
    "test_utils",
]

[profile.release]
debug = false
strip = "debuginfo"

[profile.bench]
debug = true
