[workspace]
members = [
    "crates/sui-network",
    "crates/x",
    "faucet",
    "sui",
    "sui/open_rpc",
    "sui/open_rpc/macros",
    "sui_core",
    "sui_programmability/adapter",
    "sui_programmability/adapter/transactional-tests",
    "sui_programmability/framework",
    "sui_programmability/transactional-test-runner",
    "sui_programmability/verifier",
    "sui_types",
    "test_utils",
]

[profile.release]
debug = false
strip = "debuginfo"

[profile.bench]
debug = true
