[workspace]
members = [
        "fastpay_core",
        "fastpay",
        "fastx_programmability/adapter",
        "fastx_programmability/framework",
	"fastx_types",
]

[profile.release]
debug = true

[profile.bench]
debug = true
