[workspace]
members = [
        "sui_core",
        "sui",
        "fastx_programmability/adapter",
        "fastx_programmability/framework",
	"fastx_types",
]

[profile.release]
debug = true

[profile.bench]
debug = true
