[workspace]
members = [
        "sui_core",
        "sui",
        "sui_programmability/adapter",
        "sui_programmability/framework",
	"sui_types",
        "faucet",
        "test_utils"
]

[profile.release]
debug = false
strip = "debuginfo"

[profile.bench]
debug = true
