[workspace]
members = [
        "sui_core",
        "sui",
        "sui_programmability/adapter",
        "sui_programmability/framework",
	"sui_types",
]

[profile.release]
debug = true

[profile.bench]
debug = true
