[workspace]
members = [
    "crates/sui-adapter",
    "crates/sui-adapter-transactional-tests",
    "crates/sui-config",
    "crates/sui-faucet",
    "crates/sui-framework",
    "crates/sui-framework-build",
    "crates/sui-gateway",
    "crates/sui-json",
    "crates/sui-network",
    "crates/sui-node",
    "crates/sui-open-rpc",
    "crates/sui-open-rpc-macros",
    "crates/sui-transactional-test-runner",
    "crates/sui-types",
    "crates/sui-verifier",
    "crates/sui-verifier-transactional-tests",
    "crates/test-utils",
    "crates/x",
    "sui",
    "sui_core",
    "sui_storage",
]

[profile.release]
debug = false
strip = "debuginfo"

[profile.bench]
debug = true
