packages:
  - 'sdk/**'
  - 'apps/**'
  - 'dapps/**'
  - 'examples/trading/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!sdk/create-dapp/templates'
  - '!sdk/typescript/*/**'
  - '!sdk/typescript/scripts'
  - '!sdk/typescript/builder'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/client'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/bcs'
  - '!sdk/typescript/zklogin'
