packages:
    - 'sdk/**'
    - 'apps/**'
    - 'dapps/**'
    - '!**/dist/**'
    - '!sdk/typescript/builder'
    - '!sdk/typescript/client'
    - '!sdk/typescript/cryptography'
    - '!sdk/typescript/faucet'
    - '!sdk/typescript/transactions'
    - '!sdk/typescript/*/**'
