[package]
name = "telemetry-subscribers"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Evan Chan <echan@mystenlabs.com>"]
description = "Library for common telemetry and observability functionality"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
console-subscriber = { workspace = true, optional = true }
crossterm.workspace = true
once_cell.workspace = true
prometheus.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
workspace-hack.workspace = true
opentelemetry = { version = "0.20.0", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.13.0", features = ["grpc-tonic"], optional = true }
tracing-opentelemetry = { version = "0.21.0", optional = true }
tokio.workspace = true

[features]
default = ["otlp"]
tokio-console = ["console-subscriber"]
otlp = ["tracing-opentelemetry", "opentelemetry", "opentelemetry-otlp"]

[dev-dependencies]
camino.workspace = true
