[package]
name = "sui-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_with = { version = "1.13.0" }
serde_json = "1.0.80"
base64ct = { version = "1.5.0", features = ["alloc"] }
rand = "0.7.3"
dirs = "4.0.0"
multiaddr = "0.14.0"
debug-ignore = { version = "1.0.2", features = ["serde"] }
tracing = "0.1.34"

narwhal-config = { git = "https://github.com/MystenLabs/narwhal", rev = "23745f48103656eae4a4205d0b3edd53ad8894de", package = "config" }
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "23745f48103656eae4a4205d0b3edd53ad8894de", package = "crypto" }
move-binary-format = { git = "https://github.com/move-language/move", rev = "8958b40e97a4f94a588e5365fdb90ec18f00d888" }

sui-framework = { path = "../../sui_programmability/framework" }
sui-types = { path = "../../sui_types" }
