[package]
name = "sui-move"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.36"
clap = { version = "3.2.17", features = ["derive"] }
serde_json = "1.0.88"
serde_yaml = "0.8.26"
git-version = "0.3.5"
const-str = "0.5.3"
once_cell = { version = "1.16", optional = true }

sui-core = { path = "../sui-core", optional = true }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
sui-protocol-config = { path = "../sui-protocol-config" }
sui-types = { path = "../sui-types" }
sui-cost-tables = { path = "../sui-cost-tables" }

fastcrypto.workspace = true
colored = "2.0.0"

telemetry-subscribers.workspace = true

################################################################
# Intentionally keeping the same list of Move dependencies as the workspace level Cargo.toml,
# so bumping versions on these dependencies are covered by the Move prover CI.
move-binary-format = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-bytecode-utils = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-bytecode-verifier = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-cli = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-compiler = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-core-types = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54", features = ["address32"] }
move-disassembler = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-package = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-unit-test = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-vm-test-utils = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-command-line-common = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-transactional-test-runner = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-prover = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-prover-boogie-backend = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-stackless-bytecode = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
move-symbol-pool = { git = "https://github.com/move-language/move", rev = "3ebc7eef2c41d5360cc5c0ea08ee9a4002cdba54" }
################################################################

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl = "^0.5"

[dev-dependencies]
tempfile = "3.3.0"
futures = "0.3.23"
prometheus = "0.13.3"

jsonrpsee = { version = "0.16.2", features = ["jsonrpsee-core"] }

test-utils = { path = "../test-utils" }
rand = "0.8.5"
move-package.workspace = true
sui-core = { path = "../sui-core" }
sui-node = { path = "../sui-node" }
sui-macros = { path = "../sui-macros" }
sui-simulator = { path = "../sui-simulator" }
mysten-metrics = { path = "../mysten-metrics" }

assert_cmd = "2.0.6"

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[features]
default = []
build = []
coverage = []
disassemble = []
prove = []
unit_test = ["build", "dep:once_cell", "dep:sui-core"]
calibrate = []
all = ["build", "coverage", "disassemble", "prove", "unit_test", "calibrate"]
