[package]
name = "sui-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format = { git = "https://github.com/diem/move", rev = "2f7ba92ced1f6a8efed64dbf9d7bad3ee5003203" }
move-bytecode-verifier = { git = "https://github.com/diem/move", rev = "2f7ba92ced1f6a8efed64dbf9d7bad3ee5003203" }
move-core-types = { git = "https://github.com/diem/move", rev = "2f7ba92ced1f6a8efed64dbf9d7bad3ee5003203", features = ["address20"] }
move-disassembler = { git = "https://github.com/diem/move", rev = "2f7ba92ced1f6a8efed64dbf9d7bad3ee5003203" }
move-ir-types = { git = "https://github.com/diem/move", rev = "2f7ba92ced1f6a8efed64dbf9d7bad3ee5003203" }

sui-types = { path = "../../sui_types" }
