[package]
name = "test_utils"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
tokio = { version = "1.16.1", features = ["sync", "rt"] }
bytes = "1.1.0"
futures = "0.3.21"
async-trait = "0.1.52"
log = "0.4.14"
rand = "0.7.3"
rocksdb = "0.18.0"

sui-types = { path = "../sui_types" }
sui-network = { path = "../network_utils" }