[package]
name = "test-utils"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
futures = "0.3.21"
rand = "0.7.3"
tempfile = "3.3.0"
bcs = "0.1.3"
jsonrpsee-http-server = "0.13.1"
jsonrpsee-http-client = "0.13.1"
prometheus = "0.13.1"

sui = { path = "../sui" }
sui-adapter = { path = "../sui-adapter" }
sui-config = { path = "../sui-config" }
sui-core = { path = "../sui-core" }
sui-framework = { path = "../sui-framework" }
sui-gateway = { path = "../sui-gateway" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-api = { path = "../sui-json-rpc-api" }
sui-node = { path = "../sui-node" }
sui-swarm = { path = "../sui-swarm" }
sui-types = { path = "../sui-types" }

move-package = { git = "https://github.com/move-language/move", rev = "ae62d5f1955a9b92c3ddd31d3cc4467f9aff76ae" }
move-core-types = { git = "https://github.com/move-language/move", rev = "ae62d5f1955a9b92c3ddd31d3cc4467f9aff76ae", features = ["address20"] }

workspace-hack = { path = "../workspace-hack"}
