[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../sui_programmability/framework/deps/move-stdlib/" }
Sui = { local = "../../../sui_programmability/framework/" }

[addresses]
Tutorial = "0x0"

