[package]
name = "FastX"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "346301f33b3489bb4e486ae6c0aa5e030223b492" }

[addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x2"

[dev-addresses]
Std = "0x1"
FastX = "0x2"
Examples = "0x2"
