[package]
name = "sui-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
proc-macro2 = "1"
quote = "1"
syn = "1"

[target.'cfg(madsim)'.dependencies]
madsim-macros = { path = "../../../madsim-fork/madsim-macros" }
