[package]
name = "service-boilerplate"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
workspace.anyhow = true
workspace.axum = true
workspace.mysten-service = true
workspace.prometheus = true
workspace.tracing = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
