[package]
name = "fastx-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.12.3"
bcs = "0.1.3"
bincode = "1.3.1"
failure = "0.1.8"
futures = "0.3.5"
rand = "0.7.3"
serde = { version = "1.0.115", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }
ed25519 = { version = "1.0.1"}
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
serde-name = "0.1.2"
sha3 = "0.9.1"
structopt = "0.3.21"
thiserror = "1.0"

move-binary-format = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
move-core-types = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
