[package]
name = "fastx-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
base64 = "0.13.0"
bcs = "0.1.3"
bincode = "1.3.3"
failure = "0.1.8"
futures = "0.3.5"
rand = "0.7.3"
serde = { version = "1.0.133", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
ed25519 = "1.3.0"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
serde-name = "0.2.0"
sha3 = "0.9"
structopt = "0.3.25"
thiserror = "1.0.30"

move-binary-format = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
move-core-types = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
