[package]
name = "sui-adapter"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local fastX development"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bcs = "0.1.3"
once_cell = "1.9.0"
structopt = "0.3.26"

move-binary-format = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
move-bytecode-utils = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
move-bytecode-verifier = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
move-core-types = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5", features=["address20"] }
move-cli = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
move-vm-runtime = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
move-vm-types = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }

sui-framework = { path = "../framework" }
sui-verifier = { path = "../verifier" }
sui-types = { path = "../../sui_types" }

[dev-dependencies]
move-package = { git = "https://github.com/diem/move", rev="1e5e36cb1fede8073c8688886a0943bb5bfe40d5" }
