[package]
name = "fastx-adapter"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local fastX development"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.3"
once_cell = "1.9.0"
structopt = "0.3.25"

move-binary-format = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }
move-bytecode-utils = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }
move-bytecode-verifier = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }
move-core-types = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }
move-cli = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }
move-vm-runtime = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }

fastx-framework = { path = "../framework" }
fastx-verifier = { path = "../verifier" }
fastx-types = { path = "../../fastx_types" }

[dev-dependencies]
datatest-stable = "0.1.1"
move-package = { git = "https://github.com/diem/move", rev="d253bf1c21314679d17e6935116f30baf409f264" }

[[bin]]
name = "fastx"
path = "src/main.rs"

[[test]]
name = "cli_testsuite"
harness = false
