[package]
name = "fastx-adapter"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local fastX development"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
structopt = "0.3.21"
sha3 = "0.9.1"

## uncomment for debugging with local copy of diem repo
# move-binary-format = { path = "../../../diem/language/move-binary-format" }
# move-bytecode-utils = { path = "../../../diem/language/tools/move-bytecode-utils" }
# move-core-types = { path = "../../../diem/language/move-core/types" }
# move-cli = { path = "../../../diem/language/tools/move-cli" }
# move-vm-runtime = { path = "../../../diem/language/move-vm/runtime" }

move-binary-format = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-bytecode-utils = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-core-types = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-cli = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }
move-vm-runtime = { git = "https://github.com/diem/diem", rev="661a2d1367a64a02027e4ed8f4b18f0a37cfaa17" }

fastpay_core = { path = "../../fastpay_core" }
fastx-framework = { path = "../framework" }
fastx-verifier = { path = "../verifier" }
fastx-types = { path = "../../fastx_types" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[bin]]
name = "fastx"
path = "src/main.rs"

[[test]]
name = "cli_testsuite"
harness = false
