[package]
name = "sui-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format = { git = "https://github.com/awelc/move", rev = "8a5950f256b6d558b4dee1844a561e8ddd146432" }
move-bytecode-verifier = { git = "https://github.com/awelc/move", rev = "8a5950f256b6d558b4dee1844a561e8ddd146432" }
move-core-types = { git = "https://github.com/awelc/move", rev = "8a5950f256b6d558b4dee1844a561e8ddd146432", features = ["address20"] }

sui-types = { path = "../sui-types" }

workspace-hack = { path = "../workspace-hack"}
