[package]
name = "sui-telemetry"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true

sui-core.workspace = true

