# testnet specific values


# DB_URL could conatin sensitive info so create a k8s secret outside of this helm chart. This helm chart will expect the secret to be loaded as an env var.
# Example: kubectl create secret generic db_url --from-literal=password=<actual db url> --namespace graphql
#
# RPC_URL is also expected to be an env var so the command properly populates
command: ["/opt/sui/bin/sui-graphql-rpc", "start-server","--host","0.0.0.0","--port","8001","--db-url","$DB_URL","--node-rpc-url", "$RPC_URL","--config","/opt/sui/config/graphql.toml","--ide-title","Sui Testnet GraphQL"]

configMapName: graphql-testnet-toml

# Additional volumes on the output Deployment definition.
volumes:
 - name: graphql-testnet-toml
   configMap:
    name: graphql-testnet-toml
 - name: graphql-db-url
   secret:
     secretName: db_url
     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
 - name: graphql-testnet-toml
   mountPath: "/opt/sui/config/graphql.toml"
   subPath: "graphql.toml"
   readOnly: true

secretName: graphql-db-url

