[package]
name = "SuiSystem"
version = "0.0.1"
published-at = "0x3"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
SuiFramework = { local = "../sui-framework" }

[addresses]
sui_system = "0x3"
