[package]
name = "mysten-enoki-gas-pool"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
fastcrypto.workspace = true
mysten-metrics.workspace = true
sui-config.workspace = true
sui-json-rpc-types.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
shared-crypto.workspace = true
telemetry-subscribers.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true

anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
bcs.workspace = true
clap.workspace = true
chrono.workspace = true
eyre.workspace = true
parking_lot.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_with.workspace = true
schemars.workspace = true
tap.workspace = true
tempfile.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-retry.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
rand.workspace = true

sui-swarm-config.workspace = true
test-cluster.workspace = true

