[package]
name = "sui-network"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bytes = "1.1.0"
async-trait = "0.1.53"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
tonic = "0.7"
prost = "0.10"
bincode = "1.3.3"
serde = "1.0.136"

[dev-dependencies]
tonic-build = { version = "0.7", features = [ "prost", "transport" ] }
prost-build = "0.10.1"
