[package]
name = "sui-network"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bytes = "1.1.0"
async-trait = "0.1.53"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.34"
tonic = "0.7"
prost = "0.10"
bincode = "1.3.3"
serde = "1.0.136"
sui-types = { path = "../../sui_types" }

mysten-network = { git = "https://github.com/MystenLabs/mysten-infra", rev = "7c247967e5a5abd59ecaa75bc62b05bcdf4503fe" }

[dev-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic.git", rev = "de2e4ac077c076736dc451f3415ea7da1a61a560", default-features = false, features = [ "transport" ] }
