[package]
name = "Locked Stake"

[dependencies]
Sui = { local = "../../../crates/sui-framework/packages/sui-framework" }
SuiSystem = { local = "../../../crates/sui-framework/packages/sui-system" }

[addresses]
locked_stake = "0x0"
