[package]
name = "orchestrator"
version = "0.0.1"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
glob = "0.3.1"
color-eyre = "0.6.2"
russh = "0.38.0"
russh-keys = "0.38.0"
aws-sdk-ec2 = "0.29.0"
aws-smithy-http = "0.56"
aws-smithy-runtime-api = "0.56"
aws-config.workspace = true
clap.workspace = true
eyre.workspace = true
prettytable-rs.workspace = true
serde_json.workspace = true
futures.workspace = true
thiserror.workspace = true
rand.workspace = true
reqwest.workspace = true
async-trait.workspace = true
crossterm.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }

prometheus-parse = { git = "https://github.com/asonnino/prometheus-parser.git", rev = "75334db" }

sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-node = { path = "../sui-node" }
sui-swarm-config =  { path = "../sui-swarm-config" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tempfile = "3.6.0"

[[bin]]
name = "orchestrator"
path = "src/main.rs"
