[package]
name = "sui-json-rpc-types"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.57"
anyhow = "1.0.58"
schemars = { version = "0.8.10", features = ["either"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.83"
serde_with = { version = "1.14.0", features = ["hex"] }
colored = "2.0.0"
either = "1.7.0"
itertools = "0.10.3"
tracing = "0.1.36"

move-binary-format = { git = "https://github.com/move-language/move", rev = "547c7f79d1c46dccfcb1024005d2a796be2480ec" }
move-core-types = { git = "https://github.com/move-language/move", rev = "547c7f79d1c46dccfcb1024005d2a796be2480ec", features = ["address20"] }
move-bytecode-utils = { git = "https://github.com/move-language/move", rev = "547c7f79d1c46dccfcb1024005d2a796be2480ec" }

sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
workspace-hack = { path = "../workspace-hack"}
