[package]
name = "prometheus-closure-metric"
version.workspace = true
authors = ["Andrew Schran <aschran@mystenlabs.com>"]
repository = "https://github.com/mystenlabs/mysten-infra"
description = "Library for a Prometheus metric that computes its value by given closure at collection time"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
prometheus.workspace = true
protobuf.workspace = true
