[package]
name = "fastpay"
version = "0.1.0"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0"
bytes = "0.5.6"
clap = "2.33.3"
env_logger = "0.7.1"
futures = "0.3.5"
log = "0.4.11"
net2 = "0.2.34"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
structopt = "0.3"
tempfile = "3.2.0"
tokio = { version = "0.2.22", features = ["full"] }
rand = "0.7.3"
toml = "0.5.8"
strum = "0.23.0"
strum_macros = "0.23"
num_cpus = "1.13.1"

fastpay_core = { path = "../fastpay_core" }
fastx-types = { path = "../fastx_types" }
move-package = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
move-core-types = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }
move-bytecode-verifier = { git = "https://github.com/diem/diem", rev="346301f33b3489bb4e486ae6c0aa5e030223b492" }

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"
