name: Code Coverage
on:
  workflow_dispatch:

jobs:
  cargo-llvm-cov:
    name: Generate code coverage
    runs-on: [ubuntu-ghcloud]
    timeout-minutes: 120
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: bmwill/rust-cache@v1

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
    
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 256

      - name: Install python dependencies
        run: |
          pip install pyopenssl --upgrade
          if [ -f narwhal/benchmark/requirements.txt ]; then pip install -r narwhal/benchmark/requirements.txt; fi

      - name: Install Rust
        run: rustup update stable
        
      # - name: Run code coverage for nextest
      #   run: SUI_SKIP_SIMTESTS=1 cargo llvm-cov --ignore-run-fail --lcov --output-path lcov.info nextest

      # - name: Upload report to Codecov for nextest
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: lcov.info
      #     fail_ci_if_error: true

      - name: Run code coverage for simtest
        run: |
          ./scripts/simtest/install.sh
          ./scripts/simtest/cargo-simtest simtest codecov

      - name: Upload report to Codecov for simtest
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true          
