name: Generate and Deploy Dev Portal Hosting

on:
  push:
    branches:
      - main
    paths:
      - doc/**

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          ref: doc
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - run: yarn
      - run: yarn generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
