name: Documentation

on:
  push:
    branches: [ main, extensions ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # pin@v3
      - name: Detect Changes
        uses: './.github/actions/diffs'
        id: diff

  old-doc-folder-notice:
    name: Old doc folder notice
    needs: diff
    if: needs.diff.outputs.isDoc == 'true'
    runs-on: [ubuntu-latest]

    steps:
      - name: Output error
        run: |
          echo "::error::Sui documentation has moved from doc/* to docs/content/* folder."
          exit 1
