name: Links Checker

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:

  ## Run this workflow automatically every week
  schedule:
    - cron: '0 0 * * *'

jobs:
  link_checker:
    name: Check links and create automated issue if needed
    runs-on: ubuntu-latest
    env:
      LYCHEE_OUT: ./lychee/links-report
    steps:
      ## Check out code using Git
      - uses: actions/checkout@v3

      - name: Check all links at *.md and doc files
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          output: ${{ env.LYCHEE_OUT }}
          format: markdown
          ## Do not fail this step on broken links
          fail: true
          ## Allow pages replying with 200 (Ok)in at most 20 seconds
          ## This checks all md files in the repo
          args: >-
            --verbose
            --accept 200
            --timeout 20
            --max-concurrency 10
            --no-progress
            './**/*.md'
        env:
          ## Avoid rate limiting when checking github.com links
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
