name: Move Prover

on: pull_request

jobs:
  move-prover:
    runs-on: [ubuntu-ghcloud]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      
      - name: Prover Setup
        run: |
          crates/sui/scripts/prover_setup.sh

      - name: Prover Run
        working-directory: crates/sui-framework
        run: |
          set -o pipefail
          DOTNET_ROOT="$HOME/.dotnet"
          BIN_DIR="$HOME/bin"

          export PATH=/home/runner/.cargo/bin/:$PATH
          export DOTNET_ROOT="${DOTNET_ROOT}"
          export PATH="${DOTNET_ROOT}/tools:\$PATH"
          export Z3_EXE="${BIN_DIR}/z3"
          export CVC5_EXE="${BIN_DIR}/cvc5"
          export BOOGIE_EXE="${DOTNET_ROOT}/tools/boogie"

          /home/runner/.cargo/bin/cargo run -p sui -- move prove

