name: Move Prover

on: pull_request

jobs:
  move-prover:
    runs-on: [ubuntu-ghcloud]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
      
      - name: Prover Setup
        run: |
          crates/sui/scripts/prover_setup.sh

      - name: Prover Run
        run: |
          PATH=/home/runner/.cargo/bin/:$PATH
          SCRIPT_DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
          DOTNET_ROOT="$HOME/.dotnet"
          BIN_DIR="$HOME/bin"

          export DOTNET_ROOT="${DOTNET_ROOT}"
          export PATH="${DOTNET_ROOT}/tools:\$PATH"
          export Z3_EXE="${BIN_DIR}/z3"
          export CVC5_EXE="${BIN_DIR}/cvc5"
          export BOOGIE_EXE="${DOTNET_ROOT}/tools/boogie"

          cd "${SCRIPT_DIR}/../../sui-framework" && cargo run -p sui -- move prove

