name: Release Notes Monitor

on:
  workflow_dispatch:

jobs:
  get-list-of-prs:
    name: Get Release Notes for new PRs
    outputs:
      matrix: ${{ steps.get-pr-list.outputs.matrix }}
      new_commit_hash: ${{ steps.get-pr-list.outputs.new_commit_hash }}
      new_tag: ${{ steps.get-pr-list.outputs.new_tag }}
    runs-on: [self-hosted, self-hosted-arc]
    
    steps:
    - name: Checkout sui repo main branch
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Check for a Release Notes tag for this commit
      uses: nick-fields/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482 # pin@v2
      with:
        max_attempts: 2
        timeout_seconds: 30
        command: |
          echo "new_commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "existing_tag=$(git tag --points-at ${new_commit_hash} | grep -E 'sui_v(.*)_rel_notes' | head -n 1)" >> $GITHUB_ENV

    - name: Get list of PRs
      if: ${{ env.existing_tag == '' }}
      id: get-pr-list
      working-directory: ./
      run: |
        export previous_tag=$(git tag | grep -E 'sui_v1(.*)_rel_notes' | sort -r | head -1)
        export previous_commit_hash=$(git rev-list -n 1 ${previous_tag})

        export list_of_prs=$(git log --grep "\[x\]" --pretty=oneline --abbrev-commit ${previous_commit_hash}...${{ env.new_commit_hash }} -- crates dashboards doc docker external-crates kiosk narwhal nre sui-execution | grep -o '#[0-9]\+' | grep -o '[0-9]\+' | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=matrix::${list_of_prs}"
        echo "::set-output name=new_commit_hash::${{ env.new_commit_hash }}"

        sui_crate_version=$(cat Cargo.toml | grep "^version =" | tr -d '"' | awk '{ print $3 }')
        export new_tag=$(echo "sui_v${sui_crate_version}_$(date +%s)_rel_notes")
        echo "::set-output name=new_tag::${new_tag}"
        
  process-prs:
    name: Processing PR
    needs: [ get-list-of-prs ]
    if: ${{ needs.get-list-of-prs.outputs.new_tag != '' }}
    runs-on: [self-hosted, self-hosted-arc]
    strategy:
      matrix:
         pr: ${{ fromJson(needs.get-list-of-prs.outputs.matrix) }}

    steps:
    - name: Process PRs
      id: rel-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Processing ${{ matrix.pr }} PR"
        export rel_notes=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/MystenLabs/sui/pulls/${{ matrix.pr }}} --jq ".body" | awk '/### Release notes/{p=1; next} p' | grep '\S')
        echo "::set-output name=release_notes::${rel_notes}"
    
    - name: Post to a Slack channel
      uses: slackapi/slack-github-action@34c3fd73326693ef04728f8611669d918a2d781d # pin@v1.19.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel-id: '#test-notifications'
        payload: |
          {
            "text": "PR *${{ matrix.pr }}* Release Notes",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*PR* <https://github.com/MystenLabs/sui/pull/${{ matrix.pr }}|${{ matrix.pr }}>\n <@U03LRLPR1QX> and <@U03Q2MN3XHP> please review release notes. \n *Release Notes:*\n${{ steps.rel-notes.outputs.release_notes }}\n"
                }
              },
              {
                "type": "divider"
              }
            ]
          }

  tag:
    name: Adding ${{ needs.get-list-of-prs.outputs.new_tag }} git tag to  ${{ needs.get-list-of-prs.outputs.new_commit_hash }} commit
    needs: [ get-list-of-prs, process-prs ]
    uses: mystenlabs/sui/.github/workflows/tag.yml@eugene/release_notes_monitor_work
    with:
      sui_commit: ${{ needs.get-list-of-prs.outputs.new_commit_hash }}
      tag_name: ${{ needs.get-list-of-prs.outputs.new_tag }}
    secrets: inherit
