name: Simulator Tests

concurrency:
  group: ${{ github.workflow }}

on:
  schedule:
    - cron: '0 9 * * *' # UTC timing is every day at 1am PST
  workflow_dispatch:

jobs:
  simtest:
    permissions:
      # The "id-token: write" permission is required or Machine ID will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    runs-on: [ self-hosted, self-hosted-arc ]

    steps:
      - name: Install Teleport
        uses: teleport-actions/setup@75c810ac63a7e9b28ca4795c6111619f2a13ac71 # pin@v1
        with:
          version: 11.3.1
      - name: Authorize against Teleport
        id: auth
        uses: teleport-actions/auth@6e73aa03a98e781ca6692817fbb6e554640a56b3 # pin@v1
        with:
          # Specify the publically accessible address of your Teleport proxy.
          proxy: proxy.mysten-int.com:443
          # Specify the name of the join token for your bot.
          token: sui-simtest-token
          # Specify the length of time that the generated credentials should be
          # valid for. This is optional and defaults to "1h"
          certificate-ttl: 2h
      - name: Run simtest
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ssh ubuntu@simtest-01 "which cargo" # running a test command

  # notify:
  #   name: Notify
  #   needs: [simtest]
  #   runs-on: ubuntu-latest
  #   if: always() # always notify

  #   steps:
  #   - uses: technote-space/workflow-conclusion-action@v3

  #   - name: Checkout sui repo main branch
  #     uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3
    
  #   - name: Get sui commit
  #     env:
  #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: |
  #       export sui_sha=$(git rev-parse HEAD)
  #       echo "sui_sha=${sui_sha}" >> $GITHUB_ENV

  #   - name: Get link to logs
  #     env:
  #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: |
  #       gh_job_link=$(gh api -X GET 'repos/MystenLabs/sui/actions/runs/${{ github.run_id }}/jobs' --jq '.jobs.[0].html_url')
  #       echo "gh_job_link=${gh_job_link}" >> $GITHUB_ENV        

  #   - name: Post to slack
  #     uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302 # pin@v1.21.0
  #     env:
  #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #       SUI_SHA: ${{ env.sui_sha }}
  #       GH_JOB_LINK: ${{ env.gh_job_link }}
  #     with:
  #       channel-id: 'simtest-nightly'
  #       payload: |
  #         {
  #           "text": "*${{ github.workflow }}* workflow status: `${{ env.WORKFLOW_CONCLUSION }}`",
  #           "blocks": [
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "*${{ github.workflow }}* workflow status: `${{ env.WORKFLOW_CONCLUSION }}`"
  #               }
  #             },
  #             {
  #               "type": "divider"
  #             },
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "Sui commit: <https://github.com/MystenLabs/sui/commit/${{ env.SUI_SHA }}|${{ env.SUI_SHA }}> \nRun: <${{ env.GH_JOB_LINK }}|${{ github.run_id }}>"
  #               }
  #             },
  #             {
  #               "type": "divider"
  #             },
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "To debug failures: `tsh ssh ubuntu@simtest-01` and look in the `/home/ubuntu/simtest_logs/{date}` folder"
  #               }
  #             }
  #           ]
  #         }
