name: Sui Protocol Version Monitor

concurrency:
  group: sui-protocol-version-monitor

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: "devnet"
        options:
        - devnet
        - testnet
        - mainnet

jobs:
  test:
    name: Sui Protocol Version Monitor
    runs-on: [self-hosted, self-hosted-arc]

    steps:
    - name: Download an artifact for the last saved ${{ inputs.environment }} protocol version
      continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.environment }}-protocol-version
        path: /tmp/${{ inputs.environment }}_saved_protocol_version.txt

    - name: Read last saved protocol version for ${{ inputs.environment }}
      continue-on-error: true
      shell: bash
      run: |
        echo "saved_protocol_version=`cat /tmp/${{ inputs.environment }}_saved_protocol_version.txt`" >> $GITHUB_ENV

    - name: Read live protocol version in ${{ inputs.environment }}
      working-directory: ./
      run: | 
        curl -s https://fullnode.${{ inputs.environment }}.sui.io:443 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0", "method":"suix_getLatestSuiSystemState", "params":[], "id":1}' | jq -r '.result.protocolVersion' > /tmp/${{ inputs.environment }}_current_protocol_version.txt
        echo "current_protocol_version=`cat /tmp/${{ inputs.environment }}_current_protocol_version.txt`" >> $GITHUB_ENV

    - name: Checkout sui source
      if: ${{ env.current_protocol_version > env.saved_protocol_version }}
      uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # pin@v3

    - name: Update framework/${{ inputs.environment }}
      if: ${{ env.current_protocol_version > env.saved_protocol_version }}
      uses: devvspaces/merge-branches@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        from_branch: ${{ inputs.environment }}
        to_branch: framework/${{ inputs.environment }}

    - name: Upload an artifact for current ${{ inputs.environment }} protocol version
      if: ${{ env.current_protocol_version > env.saved_protocol_version }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.environment }}-protocol-version
        path: /tmp/${{ inputs.environment }}_current_protocol_version.txt
