name: Wallet Extension PR Comment

# NOTE: This workflow run indirection is used to securely comment on PRs when
# wallet builds are completed.
on:
  workflow_run:
    workflows: ["Wallet Extension PR Checks"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });

            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "wallet-extension"
            })[0];

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          comment_includes: "💳 Wallet Extension"
          message: |
            💳 Wallet Extension has been built, you can download the packaged extension here: https://github.com/MystenLabs/sui/actions/runs/${{ github.run_id }}#artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
