[package]
name = "sui-authority-aggregation"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
sui-types.workspace = true
mysten-metrics.workspace = true
tokio.workspace = true
tracing.workspace = true
futures.workspace = true
