[package]
name = "sui-proc-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1.0.104"

[target.'cfg(msim)'.dependencies]
msim-macros = { git = "https://github.com/MystenLabs/mysten-sim.git", rev = "8190dcd907e45755d48ab14992f8df5ac31dacc9", package = "msim-macros" }
